#!/bin/bash
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# run this script from the component's root folder to deploy the scenario to device.
#

TARGET_SSHUSER=
TARGET_IP=localhost
TARGET_DIRECTORY="/tmp"
DEPLOYMENT_DIRECTORY=SystemSimpleJoystickTiagoNavigation.deployment/

echo "#######################################################"
echo "## Deployment of Device LocalPC / $TARGET_IP"
echo "#######################################################"
echo "Target SSH user:      $TARGET_SSHUSER"
echo "Target IP:            $TARGET_IP"
echo "Target directory:     $TARGET_DIRECTORY"
echo "Deployment directory: $DEPLOYMENT_DIRECTORY"

echo "Working directory of deployment script: "`pwd`

echo Sourcing referenced projects
source src-gen/deployment/referenced-projects

DEPLOY_LIBRARIES_USER=""
echo "Sourcing pre-deployment script for SmartGazeboBaseServer... (errors might be ignored)"
DEPLOY_LIBRARIES=""
DEPLOY_COMPONENT_FILES=""
source src/predeploy-SmartGazeboBaseServer.sh 2>&1

for I in $DEPLOY_LIBRARIES; do
	if [ -e "$SMART_ROOT_ACE/bin/$I" ]; then
		FILE="$SMART_ROOT_ACE/bin/$I"
	else
		FILE="$SMART_ROOT_ACE/lib/$I"
	fi
	DEPLOY_LIBRARIES_USER="$DEPLOY_LIBRARIES_USER $FILE"
done

DEPLOY_COMPONENT_FILES_PATHS_SmartGazeboBaseServer=""
for I in $DEPLOY_COMPONENT_FILES; do
	if ls $REFERENCED_PROJECT_SmartGazeboBaseServer/$I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_SmartGazeboBaseServer="$DEPLOY_COMPONENT_FILES_PATHS_SmartGazeboBaseServer $REFERENCED_PROJECT_SmartGazeboBaseServer/$I"
	elif ls $I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_SmartGazeboBaseServer="$DEPLOY_COMPONENT_FILES_PATHS_SmartGazeboBaseServer $I"
	fi
done

echo
echo "Sourcing pre-deployment script for SmartJoystickNavigation... (errors might be ignored)"
DEPLOY_LIBRARIES=""
DEPLOY_COMPONENT_FILES=""
source src/predeploy-SmartJoystickNavigation.sh 2>&1

for I in $DEPLOY_LIBRARIES; do
	if [ -e "$SMART_ROOT_ACE/bin/$I" ]; then
		FILE="$SMART_ROOT_ACE/bin/$I"
	else
		FILE="$SMART_ROOT_ACE/lib/$I"
	fi
	DEPLOY_LIBRARIES_USER="$DEPLOY_LIBRARIES_USER $FILE"
done

DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickNavigation=""
for I in $DEPLOY_COMPONENT_FILES; do
	if ls $REFERENCED_PROJECT_SmartJoystickNavigation/$I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickNavigation="$DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickNavigation $REFERENCED_PROJECT_SmartJoystickNavigation/$I"
	elif ls $I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickNavigation="$DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickNavigation $I"
	fi
done

echo
echo "Sourcing pre-deployment script for SmartJoystickServer... (errors might be ignored)"
DEPLOY_LIBRARIES=""
DEPLOY_COMPONENT_FILES=""
source src/predeploy-SmartJoystickServer.sh 2>&1

for I in $DEPLOY_LIBRARIES; do
	if [ -e "$SMART_ROOT_ACE/bin/$I" ]; then
		FILE="$SMART_ROOT_ACE/bin/$I"
	else
		FILE="$SMART_ROOT_ACE/lib/$I"
	fi
	DEPLOY_LIBRARIES_USER="$DEPLOY_LIBRARIES_USER $FILE"
done

DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickServer=""
for I in $DEPLOY_COMPONENT_FILES; do
	if ls $REFERENCED_PROJECT_SmartJoystickServer/$I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickServer="$DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickServer $REFERENCED_PROJECT_SmartJoystickServer/$I"
	elif ls $I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickServer="$DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickServer $I"
	fi
done

echo


DEPL_FILES="
$SMART_ROOT_ACE/lib/libAceSmartSoftKernel.so
$SMART_ROOT_ACE/lib/libSmartProperty.so.*
src-gen/deployment/tiler.sh
src-gen/deployment/start-LocalPC.sh
$SMART_ROOT_ACE/bin/NamingService
src-gen/deployment/ns_config.ini
src/SmartGazeboBaseServer_data
src/startstop-hooks-SmartGazeboBaseServer.sh
$SMART_ROOT_ACE/bin/SmartGazeboBaseServer
src-gen/deployment/SmartGazeboBaseServer.ini
$SMART_ROOT_ACE/lib/libCommBasicObjects.so*
src/SmartJoystickNavigation_data
src/startstop-hooks-SmartJoystickNavigation.sh
$SMART_ROOT_ACE/bin/SmartJoystickNavigation
src-gen/deployment/SmartJoystickNavigation.ini
$SMART_ROOT_ACE/lib/libCommBasicObjects.so*
src/SmartJoystickServer_data
src/startstop-hooks-SmartJoystickServer.sh
$SMART_ROOT_ACE/bin/SmartJoystickServer
src-gen/deployment/SmartJoystickServer.ini
$SMART_ROOT_ACE/lib/libCommBasicObjects.so*

$DEPLOY_LIBRARIES_USER
"

FILES_MISSING=false
for FILE in $DEPL_FILES; do
	if [ ! -e $FILE ]; then
		echo "Deployment: No such file or directory: $FILE"
		FILES_MISSING=true
	fi
done

if [ "$FILES_MISSING" = "true" ]; then
	echo
	echo "ERROR: FILES ARE MISSING FROM THE DEPLOYMENT (see above). Did you compile all components?"
	echo 
	exit 1
fi


if [ "$1" = "local" ]; then
	# local deployment
	mkdir -p $DEPLOYMENT_DIRECTORY
	rsync -l -r -v --progress --exclude ".svn" $DEPL_FILES $DEPLOYMENT_DIRECTORY/LocalPC
else
	# remote deployment
	SSH_TARGET=localhost:$TARGET_DIRECTORY/$DEPLOYMENT_DIRECTORY
	echo "Deployment to $SSH_TARGET"
	ssh localhost mkdir -p $TARGET_DIRECTORY/$DEPLOYMENT_DIRECTORY
	
	TMPDIR=$(mktemp -d --suffix=.deployment) || exit 1
	echo "Temporary directory: $TMPDIR"
	trap "rm -rf $TMPDIR" EXIT
	
	# collect files in $TMPDIR
	#rsync -l -r -v --progress --exclude ".svn" $DEPL_FILES $TMPDIR/
	cp -rv $DEPL_FILES $TMPDIR 2>&1
#rsync -l -r -v --progress --exclude ".svn" $DEPLOY_COMPONENT_FILES_PATHS_SmartGazeboBaseServer $TMPDIR/SmartGazeboBaseServer_data/
if [ ! "$DEPLOY_COMPONENT_FILES_PATHS_SmartGazeboBaseServer" = "" ]; then
	cp -rv $DEPLOY_COMPONENT_FILES_PATHS_SmartGazeboBaseServer $TMPDIR/SmartGazeboBaseServer_data/ 2>&1
fi

cp -v $REFERENCED_PROJECT_SmartGazeboBaseServer/smartsoft/src/startstop-hooks.sh $TMPDIR/startstop-hooks-component-SmartGazeboBaseServer.sh 2>/dev/null
#rsync -l -r -v --progress --exclude ".svn" $DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickNavigation $TMPDIR/SmartJoystickNavigation_data/
if [ ! "$DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickNavigation" = "" ]; then
	cp -rv $DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickNavigation $TMPDIR/SmartJoystickNavigation_data/ 2>&1
fi

cp -v $REFERENCED_PROJECT_SmartJoystickNavigation/smartsoft/src/startstop-hooks.sh $TMPDIR/startstop-hooks-component-SmartJoystickNavigation.sh 2>/dev/null
#rsync -l -r -v --progress --exclude ".svn" $DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickServer $TMPDIR/SmartJoystickServer_data/
if [ ! "$DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickServer" = "" ]; then
	cp -rv $DEPLOY_COMPONENT_FILES_PATHS_SmartJoystickServer $TMPDIR/SmartJoystickServer_data/ 2>&1
fi

cp -v $REFERENCED_PROJECT_SmartJoystickServer/smartsoft/src/startstop-hooks.sh $TMPDIR/startstop-hooks-component-SmartJoystickServer.sh 2>/dev/null
	# actually deploy:
	rsync -z -l -r -v --progress --exclude ".svn" -e ssh $TMPDIR/ $SSH_TARGET
fi


if [ "$?" != "0" ]; then
	echo "ERROR: Files could not be deployed to remote host."
	#gdialog --title ERROR --msgbox "Files could not be deployed host."
	exit 1
fi

echo -e "\n\nDeployment to device LocalPC finished.\n\n"
