#!/bin/sh
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# start script for device C26_11_RobotA


PID_XTERM="/var/tmp/start-C26_11_RobotA-xterms.pid"
PID_COMPONENT_NAMES="/var/tmp/start-C26_11_RobotA-component-names.pid"

SCRIPT_DIR=`pwd`
SCRIPT_NAME=start-C26_11_RobotA.sh

export SMART_ROOT_DEPLOYMENT=$SCRIPT_DIR

#######
## case
case "$1" in
	    
	    
#########################################################################################
## start
start)

true > $PID_XTERM
true > $PID_COMPONENT_NAMES

echo "Starting scenario..."
date -R

# CONFIGURE NAMING SERVICE
	export SMART_NS_ADDR=c26-11-robota:20002

echo "Stopping Naming Service..."
killall AceSmartSoftNamingService &
test -e SMART_NAMES && rm -f SMART_NAMES
sleep 1
echo Starting Naming Service...
rm -f AceSmartSoftNamingService.log
xterm -l -lf AceSmartSoftNamingService.log -title "AceSmartSoftNamingService" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; ./NamingService/AceSmartSoftNamingService --ns-port 20002 --ns-dir ./ --ns-file SMART_NAMES --filename=ns_config.ini; echo; echo; echo 'Naming Service exited'; /bin/bash" &
echo $! >> $PID_XTERM
echo AceSmartSoftNamingService >> $PID_COMPONENT_NAMES
sleep 1

## start components
export SMART_IP=c26-11-robota
echo "starting components..."

# Component instance SmartCdlServer
echo
echo "############################################"
echo "## Starting component instance SmartCdlServer"
cd $SCRIPT_DIR
echo "executing startstop-hooks-SmartCdlServer.sh (errors might be ignored)"
bash startstop-hooks-SmartCdlServer.sh pre-start
cd $SCRIPT_DIR/SmartCdlServer_data
rm -f "../SmartCdlServer.log"
xterm -l -lf "../SmartCdlServer.log" -title "SmartCdlServer@C26_11_RobotA Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartCdlServer -filename=$SCRIPT_DIR/SmartCdlServer.ini; echo; echo; echo 'SmartCdlServer exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartCdlServer >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-SmartCdlServer.sh post-start
echo -e "\n\n\n"

# Component instance SmartLaserLMS200Server
echo
echo "############################################"
echo "## Starting component instance SmartLaserLMS200Server"
cd $SCRIPT_DIR
echo "executing startstop-hooks-SmartLaserLMS200Server.sh (errors might be ignored)"
bash startstop-hooks-SmartLaserLMS200Server.sh pre-start
cd $SCRIPT_DIR/SmartLaserLMS200Server_data
rm -f "../SmartLaserLMS200Server.log"
xterm -l -lf "../SmartLaserLMS200Server.log" -title "SmartLaserLMS200Server@C26_11_RobotA Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartLaserLMS200Server -filename=$SCRIPT_DIR/SmartLaserLMS200Server.ini; echo; echo; echo 'SmartLaserLMS200Server exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartLaserLMS200Server >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-SmartLaserLMS200Server.sh post-start
echo -e "\n\n\n"

# Component instance SmartMapperGridMap
echo
echo "############################################"
echo "## Starting component instance SmartMapperGridMap"
cd $SCRIPT_DIR
echo "executing startstop-hooks-SmartMapperGridMap.sh (errors might be ignored)"
bash startstop-hooks-SmartMapperGridMap.sh pre-start
cd $SCRIPT_DIR/SmartMapperGridMap_data
rm -f "../SmartMapperGridMap.log"
xterm -l -lf "../SmartMapperGridMap.log" -title "SmartMapperGridMap@C26_11_RobotA Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartMapperGridMap -filename=$SCRIPT_DIR/SmartMapperGridMap.ini; echo; echo; echo 'SmartMapperGridMap exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartMapperGridMap >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-SmartMapperGridMap.sh post-start
echo -e "\n\n\n"

# Component instance SmartPioneerBaseServer
echo
echo "############################################"
echo "## Starting component instance SmartPioneerBaseServer"
cd $SCRIPT_DIR
echo "executing startstop-hooks-SmartPioneerBaseServer.sh (errors might be ignored)"
bash startstop-hooks-SmartPioneerBaseServer.sh pre-start
cd $SCRIPT_DIR/SmartPioneerBaseServer_data
rm -f "../SmartPioneerBaseServer.log"
xterm -l -lf "../SmartPioneerBaseServer.log" -title "SmartPioneerBaseServer@C26_11_RobotA Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartPioneerBaseServer -filename=$SCRIPT_DIR/SmartPioneerBaseServer.ini; echo; echo; echo 'SmartPioneerBaseServer exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartPioneerBaseServer >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-SmartPioneerBaseServer.sh post-start
echo -e "\n\n\n"

# Component instance SmartPlannerBreadthFirstSearch
echo
echo "############################################"
echo "## Starting component instance SmartPlannerBreadthFirstSearch"
cd $SCRIPT_DIR
echo "executing startstop-hooks-SmartPlannerBreadthFirstSearch.sh (errors might be ignored)"
bash startstop-hooks-SmartPlannerBreadthFirstSearch.sh pre-start
cd $SCRIPT_DIR/SmartPlannerBreadthFirstSearch_data
rm -f "../SmartPlannerBreadthFirstSearch.log"
xterm -l -lf "../SmartPlannerBreadthFirstSearch.log" -title "SmartPlannerBreadthFirstSearch@C26_11_RobotA Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartPlannerBreadthFirstSearch -filename=$SCRIPT_DIR/SmartPlannerBreadthFirstSearch.ini; echo; echo; echo 'SmartPlannerBreadthFirstSearch exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartPlannerBreadthFirstSearch >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-SmartPlannerBreadthFirstSearch.sh post-start
echo -e "\n\n\n"

# Component instance SmartRobotConsole
echo
echo "############################################"
echo "## Starting component instance SmartRobotConsole"
cd $SCRIPT_DIR
echo "executing startstop-hooks-SmartRobotConsole.sh (errors might be ignored)"
bash startstop-hooks-SmartRobotConsole.sh pre-start
cd $SCRIPT_DIR/SmartRobotConsole_data
rm -f "../SmartRobotConsole.log"
xterm -l -lf "../SmartRobotConsole.log" -title "SmartRobotConsole@C26_11_RobotA Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartRobotConsole -filename=$SCRIPT_DIR/SmartRobotConsole.ini; echo; echo; echo 'SmartRobotConsole exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartRobotConsole >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-SmartRobotConsole.sh post-start
echo -e "\n\n\n"


cd $SCRIPT_DIR

;; ## start


#########################################################################################
## stop
stop)
cd $SCRIPT_DIR
bash startstop-hooks-SmartCdlServer.sh pre-stop
bash startstop-hooks-SmartLaserLMS200Server.sh pre-stop
bash startstop-hooks-SmartMapperGridMap.sh pre-stop
bash startstop-hooks-SmartPioneerBaseServer.sh pre-stop
bash startstop-hooks-SmartPlannerBreadthFirstSearch.sh pre-stop
bash startstop-hooks-SmartRobotConsole.sh pre-stop

echo "kill all components..."

for I in `cat $PID_COMPONENT_NAMES`; do
        echo $I
        killall -2 $I
done
rm $PID_COMPONENT_NAMES

sleep 3

for I in `cat $PID_XTERM`; do
        echo $I
        kill -2 $I
done
rm $PID_XTERM



test -e SMART_NAMES && rm -f SMART_NAMES

bash startstop-hooks-SmartCdlServer.sh post-stop
bash startstop-hooks-SmartLaserLMS200Server.sh post-stop
bash startstop-hooks-SmartMapperGridMap.sh post-stop
bash startstop-hooks-SmartPioneerBaseServer.sh post-stop
bash startstop-hooks-SmartPlannerBreadthFirstSearch.sh post-stop
bash startstop-hooks-SmartRobotConsole.sh post-stop


# collect log files
ls -l *.log && (
	pwd
	tar czvf C26_11_RobotA-logs-$(date +"%Y%m%d%H%M").tar.gz *.log
	rm *.log
)

;; ## stop



#########################################################################################
## menu

menu-start)
	bash $SCRIPT_NAME start
	cd $SCRIPT_DIR
	bash $SCRIPT_NAME menu
;;

menu-stop)
	bash $SCRIPT_NAME stop
	cd $SCRIPT_DIR
	bash $SCRIPT_NAME menu
;;

menu-tile)
	bash tiler.sh
	cd $SCRIPT_DIR
	bash $SCRIPT_NAME menu
;;

menu)

#wmctrl -r :ACTIVE: -b add,above
ACTION=$(whiptail --title "Scenario Control" --menu "Choose an option" 12 35 4 "menu-start" "Start Scenario" "menu-stop" "Stop Scenario" "menu-tile" "Arrange terminals" "quit" "Quit to console" 3>&1 1>&2 2>&3)
#whiptail --title "Scenario Control" --menu "Choose an option" 10 30 3 "menu-start" "Start Scenario" "menu-stop" "Stop Scenario" "quit" "Quit to console" 2>/tmp/whip
#ACTION=`cat /tmp/whip`

cd $SCRIPT_DIR
bash $SCRIPT_NAME $ACTION

;; ## menu

quit)
	bash $SCRIPT_NAME stop
;;
		
		
#########################################################################################
## default
*)
echo "No such parameter: $1"
echo "Usage: $SCRIPT_NAME {start|stop|menu-start|menu-stop|menu}"
exit 1
;;

esac
