#!/bin/bash
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# This script collects the generated ini-file parts and combines them into single ini-files (one for each component artefact)
#

# create ini-file GazeboBaseServer.ini
echo "create ini-file GazeboBaseServer.ini"
cp src-gen/system/GazeboBaseServer.ini src-gen/deployment/
cat src-gen/params/GazeboBaseServer.ini >> src-gen/deployment/GazeboBaseServer.ini

# create ini-file JoystickNavigation.ini
echo "create ini-file JoystickNavigation.ini"
cp src-gen/system/JoystickNavigation.ini src-gen/deployment/
cat src-gen/params/JoystickNavigation.ini >> src-gen/deployment/JoystickNavigation.ini

# create ini-file JoystickServer.ini
echo "create ini-file JoystickServer.ini"
cp src-gen/system/JoystickServer.ini src-gen/deployment/
cat src-gen/params/JoystickServer.ini >> src-gen/deployment/JoystickServer.ini

# create ini-file MapperGridMap.ini
echo "create ini-file MapperGridMap.ini"
cp src-gen/system/MapperGridMap.ini src-gen/deployment/
cat src-gen/params/MapperGridMap.ini >> src-gen/deployment/MapperGridMap.ini

# create ini-file Planner.ini
echo "create ini-file Planner.ini"
cp src-gen/system/Planner.ini src-gen/deployment/
cat src-gen/params/Planner.ini >> src-gen/deployment/Planner.ini

# create ini-file RobotConsole.ini
echo "create ini-file RobotConsole.ini"
cp src-gen/system/RobotConsole.ini src-gen/deployment/
cat src-gen/params/RobotConsole.ini >> src-gen/deployment/RobotConsole.ini

# create ini-file SmartCdlServer.ini
echo "create ini-file SmartCdlServer.ini"
cp src-gen/system/SmartCdlServer.ini src-gen/deployment/
cat src-gen/params/SmartCdlServer.ini >> src-gen/deployment/SmartCdlServer.ini

