#!/bin/sh
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# start script for device VirtualBoxImage


PID_XTERM="/var/tmp/start-VirtualBoxImage-xterms.pid"
PID_COMPONENT_NAMES="/var/tmp/start-VirtualBoxImage-component-names.pid"

SCRIPT_DIR=`pwd`
SCRIPT_NAME=start-VirtualBoxImage.sh

export SMART_ROOT_DEPLOYMENT=$SCRIPT_DIR

#######
## case
case "$1" in
	    
	    
#########################################################################################
## start
start)

true > $PID_XTERM
true > $PID_COMPONENT_NAMES

echo "Starting scenario..."
date -R

# CONFIGURE NAMING SERVICE
	export SMART_NS_ADDR=localhost:20002

echo "Stopping Naming Service..."
killall AceSmartSoftNamingService &
test -e SMART_NAMES && rm -f SMART_NAMES
sleep 1
echo Starting Naming Service...
rm -f AceSmartSoftNamingService.log
xterm -l -lf AceSmartSoftNamingService.log -title "AceSmartSoftNamingService" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; ./NamingService/AceSmartSoftNamingService --ns-port 20002 --ns-dir ./ --ns-file SMART_NAMES --filename=ns_config.ini; echo; echo; echo 'Naming Service exited'; /bin/bash" &
echo $! >> $PID_XTERM
echo AceSmartSoftNamingService >> $PID_COMPONENT_NAMES
sleep 1

## start components
export SMART_IP=localhost
echo "starting components..."

# Component instance GazeboBaseServer
echo
echo "############################################"
echo "## Starting component instance GazeboBaseServer"
cd $SCRIPT_DIR
echo "executing startstop-hooks-GazeboBaseServer.sh (errors might be ignored)"
bash startstop-hooks-GazeboBaseServer.sh pre-start
cd $SCRIPT_DIR/GazeboBaseServer_data
rm -f "../GazeboBaseServer.log"
xterm -l -lf "../GazeboBaseServer.log" -title "GazeboBaseServer@VirtualBoxImage Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartGazeboBaseServer -filename=$SCRIPT_DIR/GazeboBaseServer.ini; echo; echo; echo 'GazeboBaseServer exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartGazeboBaseServer >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-GazeboBaseServer.sh post-start
echo -e "\n\n\n"

# Component instance JoystickNavigation
echo
echo "############################################"
echo "## Starting component instance JoystickNavigation"
cd $SCRIPT_DIR
echo "executing startstop-hooks-JoystickNavigation.sh (errors might be ignored)"
bash startstop-hooks-JoystickNavigation.sh pre-start
cd $SCRIPT_DIR/JoystickNavigation_data
rm -f "../JoystickNavigation.log"
xterm -l -lf "../JoystickNavigation.log" -title "JoystickNavigation@VirtualBoxImage Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartJoystickNavigation -filename=$SCRIPT_DIR/JoystickNavigation.ini; echo; echo; echo 'JoystickNavigation exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartJoystickNavigation >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-JoystickNavigation.sh post-start
echo -e "\n\n\n"

# Component instance JoystickServer
echo
echo "############################################"
echo "## Starting component instance JoystickServer"
cd $SCRIPT_DIR
echo "executing startstop-hooks-JoystickServer.sh (errors might be ignored)"
bash startstop-hooks-JoystickServer.sh pre-start
cd $SCRIPT_DIR/JoystickServer_data
rm -f "../JoystickServer.log"
xterm -l -lf "../JoystickServer.log" -title "JoystickServer@VirtualBoxImage Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartJoystickServer -filename=$SCRIPT_DIR/JoystickServer.ini; echo; echo; echo 'JoystickServer exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartJoystickServer >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-JoystickServer.sh post-start
echo -e "\n\n\n"

# Component instance MapperGridMap
echo
echo "############################################"
echo "## Starting component instance MapperGridMap"
cd $SCRIPT_DIR
echo "executing startstop-hooks-MapperGridMap.sh (errors might be ignored)"
bash startstop-hooks-MapperGridMap.sh pre-start
cd $SCRIPT_DIR/MapperGridMap_data
rm -f "../MapperGridMap.log"
xterm -l -lf "../MapperGridMap.log" -title "MapperGridMap@VirtualBoxImage Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartMapperGridMap -filename=$SCRIPT_DIR/MapperGridMap.ini; echo; echo; echo 'MapperGridMap exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartMapperGridMap >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-MapperGridMap.sh post-start
echo -e "\n\n\n"

# Component instance Planner
echo
echo "############################################"
echo "## Starting component instance Planner"
cd $SCRIPT_DIR
echo "executing startstop-hooks-Planner.sh (errors might be ignored)"
bash startstop-hooks-Planner.sh pre-start
cd $SCRIPT_DIR/Planner_data
rm -f "../Planner.log"
xterm -l -lf "../Planner.log" -title "Planner@VirtualBoxImage Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartPlannerBreadthFirstSearch -filename=$SCRIPT_DIR/Planner.ini; echo; echo; echo 'Planner exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartPlannerBreadthFirstSearch >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-Planner.sh post-start
echo -e "\n\n\n"

# Component instance RobotConsole
echo
echo "############################################"
echo "## Starting component instance RobotConsole"
cd $SCRIPT_DIR
echo "executing startstop-hooks-RobotConsole.sh (errors might be ignored)"
bash startstop-hooks-RobotConsole.sh pre-start
cd $SCRIPT_DIR/RobotConsole_data
rm -f "../RobotConsole.log"
xterm -l -lf "../RobotConsole.log" -title "RobotConsole@VirtualBoxImage Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartRobotConsole -filename=$SCRIPT_DIR/RobotConsole.ini; echo; echo; echo 'RobotConsole exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartRobotConsole >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-RobotConsole.sh post-start
echo -e "\n\n\n"

# Component instance SmartCdlServer
echo
echo "############################################"
echo "## Starting component instance SmartCdlServer"
cd $SCRIPT_DIR
echo "executing startstop-hooks-SmartCdlServer.sh (errors might be ignored)"
bash startstop-hooks-SmartCdlServer.sh pre-start
cd $SCRIPT_DIR/SmartCdlServer_data
rm -f "../SmartCdlServer.log"
xterm -l -lf "../SmartCdlServer.log" -title "SmartCdlServer@VirtualBoxImage Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartCdlServer -filename=$SCRIPT_DIR/SmartCdlServer.ini; echo; echo; echo 'SmartCdlServer exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartCdlServer >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-SmartCdlServer.sh post-start
echo -e "\n\n\n"


cd $SCRIPT_DIR

;; ## start


#########################################################################################
## stop
stop)
cd $SCRIPT_DIR
bash startstop-hooks-GazeboBaseServer.sh pre-stop
bash startstop-hooks-JoystickNavigation.sh pre-stop
bash startstop-hooks-JoystickServer.sh pre-stop
bash startstop-hooks-MapperGridMap.sh pre-stop
bash startstop-hooks-Planner.sh pre-stop
bash startstop-hooks-RobotConsole.sh pre-stop
bash startstop-hooks-SmartCdlServer.sh pre-stop

echo "kill all components..."

for I in `cat $PID_COMPONENT_NAMES`; do
        echo $I
        killall -2 $I
done
rm $PID_COMPONENT_NAMES

sleep 3

for I in `cat $PID_XTERM`; do
        echo $I
        kill -2 $I
done
rm $PID_XTERM



test -e SMART_NAMES && rm -f SMART_NAMES

bash startstop-hooks-GazeboBaseServer.sh post-stop
bash startstop-hooks-JoystickNavigation.sh post-stop
bash startstop-hooks-JoystickServer.sh post-stop
bash startstop-hooks-MapperGridMap.sh post-stop
bash startstop-hooks-Planner.sh post-stop
bash startstop-hooks-RobotConsole.sh post-stop
bash startstop-hooks-SmartCdlServer.sh post-stop


# collect log files
ls -l *.log && (
	pwd
	tar czvf VirtualBoxImage-logs-$(date +"%Y%m%d%H%M").tar.gz *.log
	rm *.log
)

;; ## stop



#########################################################################################
## menu

menu-start)
	bash $SCRIPT_NAME start
	cd $SCRIPT_DIR
	bash $SCRIPT_NAME menu
;;

menu-stop)
	bash $SCRIPT_NAME stop
	cd $SCRIPT_DIR
	bash $SCRIPT_NAME menu
;;

menu-tile)
	bash tiler.sh
	cd $SCRIPT_DIR
	bash $SCRIPT_NAME menu
;;

menu)

#wmctrl -r :ACTIVE: -b add,above
ACTION=$(whiptail --title "Scenario Control" --menu "Choose an option" 12 35 4 "menu-start" "Start Scenario" "menu-stop" "Stop Scenario" "menu-tile" "Arrange terminals" "quit" "Quit to console" 3>&1 1>&2 2>&3)
#whiptail --title "Scenario Control" --menu "Choose an option" 10 30 3 "menu-start" "Start Scenario" "menu-stop" "Stop Scenario" "quit" "Quit to console" 2>/tmp/whip
#ACTION=`cat /tmp/whip`

cd $SCRIPT_DIR
bash $SCRIPT_NAME $ACTION

;; ## menu

quit)
	bash $SCRIPT_NAME stop
;;
		
		
#########################################################################################
## default
*)
echo "No such parameter: $1"
echo "Usage: $SCRIPT_NAME {start|stop|menu-start|menu-stop|menu}"
exit 1
;;

esac
